package com.example.languagelegends.features

val LANGUAGES = mapOf(
    "Bulgarian" to "BG",
    "Czech" to "CS",
    "Danish" to "DA",
    "German" to "DE",
    "Greek" to "EL",
    "English (British)" to "EN-GB",
    "English (American)" to "EN-US",
    "Spanish" to "ES",
    "Estonian" to "ET",
    "Finnish" to "FI",
    "French" to "FR",
    "Hungarian" to "HU",
    "Indonesian" to "ID",
    "Italian" to "IT",
    "Japanese" to "JA",
    "Korean" to "KO",
    "Lithuanian" to "LT",
    "Latvian" to "LV",
    "Norwegian" to "NB",
    "Dutch" to "NL",
    "Polish" to "PL",
    "Portuguese (Brazilian)" to "PT-BR",
    "Portuguese (European)" to "PT-PT",
    "Romanian" to "RO",
    "Russian" to "RU",
    "Slovak" to "SK",
    "Slovenian" to "SL",
    "Swedish" to "SV",
    "Turkish" to "TR",
    "Ukrainian" to "UK",
    "Chinese" to "ZH"
)